### PR TITLE
Software hardware failsafe

### PR DESCRIPTION
**Pull request by PizzaAllTheWay**
Finished implementation of ASV ESC Firmware. It works with Failsafe PCB. It arms and rearms itself once on changed from hardware to software mode or all errors have been resolved. If any failsafe triggers the thrusters stop. It also communicates with I2C buss really well.
All tested and working :D

### CODE REVIEW

**Comment by PizzaAllTheWay** [comment]
Also, @Benjamin-A I tested with the 10 minute beacon killswitch. The one where if thrusters continually get the same signal for 10 min + it will stop thrusters. And the failsafe mechanism works! By just sending inn new values after beacon killswitch goes off it will stop beeping and will automatically reset the beacon timer, the thrusters will go to its normal state and drive as before once the signal is established again :D

**Review by Benjamin-A — COMMENTED** [review]
### Looks nice.
The Fail Safe PCB [FS PCB] also has an Armed flag, this may cause confusion.
We need to document what this Software "Arming" implies, I assume toggling whether the PWM signals are sent or not.

**Comment by PizzaAllTheWay** [comment]
Changed positioning of the input and output pins so that it is easier for electrical to set up Teensy and less confusion. Also documented new changes on Wiki here: https://vortex.a2hosted.com/index.php/ASV_Fail_Safe#Teensy_connections_(SW)
Can you double check the main file with wiki and that this makes sense for you @Benjamin-A ?

**Review by Benjamin-A — APPROVED** [review]
Thank you for changing the pinout! This makes cable routing cleaner :)

**Pull request merged**
